version: "3.9"

services:
  api_one:
    build:
      context: .
      dockerfile: api_one_dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./api_one/:/api_one/
    ports:
      - "8001:8001"
    expose:
      - 8001
  api_two:
    build:
      context: .
      dockerfile: api_two_dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./api_two/:/api_two/
    ports:
      - "8002:8002"
    expose:
      - 8002
  nginx:
    build:
      context: .
      dockerfile: nginx_dockerfile
    # volumes:
    #   - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - api_one
      - api_two
  # my_proxy:
  #   image: nginx
  #   ports:
  #   - "8080:80"
  #   volumes:
  #     - ./my_nginx/nginx.conf:/etc/nginx/nginx.conf


    